openapi: 3.0.1
info:
  title: API Assessment
  description: This service provides the way to manage the glasses, frames and lenses e-commerce store.
  contact:
    name: "BlooBloom"
  version: 1.0.0

  servers:
  - url: /api/v1
    description: Review Branch v1

  tags:
  - name: admin
    description: Admins API
  - name: user
    description: Users API
  - name: health
    description: Service health
  - name: swagger
    description: Usage documentation

paths:
  /api/v1/admins/authenticate:
    post:
      summary: Authenticate admin and get JWT token
      description: Authenticate admin and get JWT token.
      security: []
      operationId: authenticateAdmin
      tags:
        - admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: admin
                password:
                  type: string
                  example: admin
      responses:
        200:
          description: OK
        204:
          description: No Content
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Caller has a valid token but it not permitted to call this operation
        500:
          description: Service or a dependency is unhealthy

  /api/v1/admins/frames/:
    get:
      summary: Get all frames
      description: Get all frames.
      security:
        - authzero: []
      operationId: getAllFrames
      tags:
        - admin
      responses:
        200:
          description: OK
        204:
          description: No Content
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Caller has a valid token but it not permitted to call this operation
        500:
          description: Service or a dependency is unhealthy
    post:
      summary: Create a new frame
      description: Create a new frame.
      security:
        - authzero: []
      operationId: addNewFrame
      tags:
        - admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: frame 1
                description:
                  type: string
                  example: dummy description
                status:
                  type: string
                  example: Active
                stock:
                  type: integer
                  example: 10
                price:
                  type: object
                  properties:
                    USD:
                      type: number
                      example: 100
                    GBP:
                      type: number
                      example: 100
                    EUR:
                      type: number
                      example: 100
                    JOD:
                      type: number
                      example: 100
                    JPY:
                      type: number
                      example: 100
      responses:
        201:
          description: OK
        204:
          description: No Content
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Caller has a valid token but it not permitted to call this operation
        500:
          description: Service or a dependency is unhealthy
  /api/v1/admins/frames/{id}:
    get:
      summary: Get a specific frame
      description: Get a specific frame.
      security:
        - authzero: []
      operationId: getSpecificFrames
      tags:
        - admin
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the frame to get
      responses:
        200:
          description: OK
        204:
          description: No Content
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Caller has a valid token but it not permitted to call this operation
        500:
          description: Service or a dependency is unhealthy
    put:
      summary: Update a specific frame
      description: Update a specific frame.
      security:
        - authzero: []
      operationId: updateSpecificFrames
      tags:
        - admin
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the frame to get
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: frame 1
                description:
                  type: string
                  example: dummy description
                status:
                  type: string
                  example: Active
                stock:
                  type: integer
                  example: 10
                price:
                  type: object
                  properties:
                    USD:
                      type: number
                      example: 100
                    GBP:
                      type: number
                      example: 100
                    EUR:
                      type: number
                      example: 100
                    JOD:
                      type: number
                      example: 100
                    JPY:
                      type: number
                      example: 100
      responses:
        200:
          description: OK
        204:
          description: No Content
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Caller has a valid token but it not permitted to call this operation
        500:
          description: Service or a dependency is unhealthy
    delete:
      summary: Remove a specific frame
      description: Remove a specific frame.
      security:
        - authzero: []
      operationId: removeSpecificFrames
      tags:
        - admin
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the frame to get
      responses:
        200:
          description: OK
        204:
          description: No Content
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Caller has a valid token but it not permitted to call this operation
        500:
          description: Service or a dependency is unhealthy
  /api/v1/admins/lenses/:
    get:
      summary: Get all lenses
      description: Get all lenses.
      security:
        - authzero: []
      operationId: getAllLenses
      tags:
        - admin
      responses:
        200:
          description: OK
        204:
          description: No Content
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Caller has a valid token but it not permitted to call this operation
        500:
          description: Service or a dependency is unhealthy
    post:
      summary: Create a new lense
      description: Create a new lense.
      security:
        - authzero: []
      operationId: addNewLense
      tags:
        - admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: lense 1
                description:
                  type: string
                  example: dummy description
                status:
                  type: string
                  example: Active
                stock:
                  type: integer
                  example: 10
                price:
                  type: object
                  properties:
                    USD:
                      type: number
                      example: 100
                    GBP:
                      type: number
                      example: 100
                    EUR:
                      type: number
                      example: 100
                    JOD:
                      type: number
                      example: 100
                    JPY:
                      type: number
                      example: 100
      responses:
        201:
          description: OK
        204:
          description: No Content
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Caller has a valid token but it not permitted to call this operation
        500:
          description: Service or a dependency is unhealthy
  /api/v1/admins/lenses/{id}:
    get:
      summary: Get a specific lense
      description: Get a specific lense.
      security:
        - authzero: []
      operationId: getSpecificLenses
      tags:
        - admin
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the lense to get
      responses:
        200:
          description: OK
        204:
          description: No Content
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Caller has a valid token but it not permitted to call this operation
        500:
          description: Service or a dependency is unhealthy
    put:
      summary: Update a specific lense
      description: Update a specific lense.
      security:
        - authzero: []
      operationId: updateSpecificLenses
      tags:
        - admin
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the lense to get
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: lense 1
                description:
                  type: string
                  example: dummy description
                status:
                  type: string
                  example: Active
                stock:
                  type: integer
                  example: 10
                price:
                  type: object
                  properties:
                    USD:
                      type: number
                      example: 100
                    GBP:
                      type: number
                      example: 100
                    EUR:
                      type: number
                      example: 100
                    JOD:
                      type: number
                      example: 100
                    JPY:
                      type: number
                      example: 100
      responses:
        200:
          description: OK
        204:
          description: No Content
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Caller has a valid token but it not permitted to call this operation
        500:
          description: Service or a dependency is unhealthy
    delete:
      summary: Remove a specific lense
      description: Remove a specific lense.
      security:
        - authzero: []
      operationId: removeSpecificLenses
      tags:
        - admin
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the lense to get
      responses:
        200:
          description: OK
        204:
          description: No Content
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Caller has a valid token but it not permitted to call this operation
        500:
          description: Service or a dependency is unhealthy

  /api/v1/users/frames/:
    get:
      summary: Get all active frames
      description: Get all active frames.
      security: []
      operationId: getAllActiveFrames
      tags:
        - user
      responses:
        200:
          description: OK
        204:
          description: No Content
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Caller has a valid token but it not permitted to call this operation
        500:
          description: Service or a dependency is unhealthy
  /api/v1/users/frames/{id}:
    get:
      summary: Get a specific frame
      description: Get a specific frame.
      security: []
      operationId: getSpecificActiveFrames
      tags:
        - user
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the frame to get
      responses:
        200:
          description: OK
        204:
          description: No Content
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Caller has a valid token but it not permitted to call this operation
        500:
          description: Service or a dependency is unhealthy
  /api/v1/users/lenses/:
    get:
      summary: Get all lenses
      description: Get all lenses.
      security: []
      operationId: getAllLenses
      tags:
        - user
      responses:
        200:
          description: OK
        204:
          description: No Content
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Caller has a valid token but it not permitted to call this operation
        500:
          description: Service or a dependency is unhealthy
  /api/v1/users/lenses/{id}:
    get:
      summary: Get a specific lense
      description: Get a specific lense.
      security: []
      operationId: getSpecificLenses
      tags:
        - user
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the lense to get
      responses:
        200:
          description: OK
        204:
          description: No Content
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Caller has a valid token but it not permitted to call this operation
        500:
          description: Service or a dependency is unhealthy
  

components:  
  securitySchemes:
    authzero:
      description: You should use JWT tokens for secure routes. 
      type: http
      scheme: bearer
      bearerFormat: JWT  